kind: Service
apiVersion: v1
metadata:
  name: app-test-cert
  namespace: default
  labels:
    app: app-test-cert
spec:
  clusterIP: 10.217.5.146
  ipFamilies:
    - IPv4
  ports:
    - name: port-1
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: port-2
      protocol: TCP
      port: 8888
      targetPort: 8888
  internalTrafficPolicy: Cluster
  clusterIPs:
    - 10.217.5.146
  type: ClusterIP
  ipFamilyPolicy: SingleStack
  sessionAffinity: None
  selector:
    app: app-test-cert
    deploymentconfig: app-test-cert
status:
  loadBalancer: {}
